/**
 * AgentItemBinary automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {AgentItem} from "./AgentItem";

/**
 * Binary agent message
 */
export interface AgentItemBinary extends AgentItem {
    type: "binary"
    mime?: string
    data?: string
}

