/**
 * AgentOutput automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {AgentItem} from "./AgentItem";
import type {AgentItemBinary} from "./AgentItemBinary";
import type {AgentItemChoice} from "./AgentItemChoice";
import type {AgentItemObject} from "./AgentItemObject";
import type {AgentItemText} from "./AgentItemText";
import type {AgentItemToolCall} from "./AgentItemToolCall";

/**
 * This object represents an agent output
 */
export interface AgentOutput {
    id?: string
    item?: AgentItemBinary|AgentItemChoice|AgentItemObject|AgentItemText|AgentItemToolCall
}

