/**
 * AgentItemChoice automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {AgentItem} from "./AgentItem";
import type {AgentItemBinary} from "./AgentItemBinary";
import type {AgentItemObject} from "./AgentItemObject";
import type {AgentItemText} from "./AgentItemText";
import type {AgentItemToolCall} from "./AgentItemToolCall";

/**
 * Choice agent message
 */
export interface AgentItemChoice extends AgentItem {
    type: "choice"
    items?: Array<AgentItemBinary|AgentItemChoice|AgentItemObject|AgentItemText|AgentItemToolCall>
}

