/**
 * AgentItemObject automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {AgentItem} from "./AgentItem";

/**
 * Structured agent message
 */
export interface AgentItemObject extends AgentItem {
    type: "object"
    payload?: any
}

