/**
 * AgentItem automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {AgentItemBinary} from "./AgentItemBinary";
import type {AgentItemChoice} from "./AgentItemChoice";
import type {AgentItemObject} from "./AgentItemObject";
import type {AgentItemText} from "./AgentItemText";
import type {AgentItemToolCall} from "./AgentItemToolCall";

/**
 * Agent item
 */
export interface AgentItem {
    type?: string
    metadata?: Record<string, any>
}

