/**
 * BackendScopeCategory automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendScopeCategoryScope} from "./BackendScopeCategoryScope";

export interface BackendScopeCategory {
    id?: number
    name?: string
    scopes?: Array<BackendScopeCategoryScope>
}

