/**
 * BackendConnectionRedirectResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Redirect response to initiate an OAuth2 flow
 */
export interface BackendConnectionRedirectResponse {
    redirectUri?: string
}

