/**
 * BackendUserCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendUser} from "./BackendUser";

export interface BackendUserCreate extends BackendUser {
    password?: string
}

