/**
 * BackendTriggerUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendTrigger} from "./BackendTrigger";

export interface BackendTriggerUpdate extends BackendTrigger {
}

