/**
 * BackendSchema automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendSchemaSource} from "./BackendSchemaSource";
import {BackendSchemaForm} from "./BackendSchemaForm";
import {CommonMetadata} from "./CommonMetadata";

export interface BackendSchema {
    id?: number
    status?: number
    name?: string
    source?: BackendSchemaSource
    form?: BackendSchemaForm
    readonly?: boolean
    metadata?: CommonMetadata
}

