/**
 * BackendIdentityCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendIdentity} from "./BackendIdentity";

export interface BackendIdentityCollection extends CommonCollection<BackendIdentity> {
}

