/**
 * BackendAppCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendApp} from "./BackendApp";
export interface BackendAppCreate extends BackendApp {
}
