/**
 * BackendDashboard automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendStatisticChart} from "./BackendStatisticChart";
import {BackendDashboardApps} from "./BackendDashboardApps";
import {BackendDashboardRequests} from "./BackendDashboardRequests";
import {BackendDashboardUsers} from "./BackendDashboardUsers";
export interface BackendDashboard {
    errorsPerOperation?: BackendStatisticChart
    incomingRequests?: BackendStatisticChart
    incomingTransactions?: BackendStatisticChart
    mostUsedOperations?: BackendStatisticChart
    timePerOperation?: BackendStatisticChart
    testCoverage?: BackendStatisticChart
    latestApps?: BackendDashboardApps
    latestRequests?: BackendDashboardRequests
    latestUsers?: BackendDashboardUsers
}
