/**
 * BackendCategoryUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendCategory} from "./BackendCategory";

export interface BackendCategoryUpdate extends BackendCategory {
}

