/**
 * BackendConfigCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {BackendConfig} from "./BackendConfig";

/**
 * A paginated collection of config objects
 */
export interface BackendConfigCollection extends CommonCollection<BackendConfig> {
}

