/**
 * BackendTrashDataCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendTrashData} from "./BackendTrashData";

/**
 * A paginated collection of deleted objects
 */
export interface BackendTrashDataCollection extends CommonCollection<BackendTrashData> {
}

