/**
 * BackendScopeCategories automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendScopeCategory} from "./BackendScopeCategory";
export interface BackendScopeCategories {
    categories?: Array<BackendScopeCategory>
}
