/**
 * BackendPlanCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendPlan} from "./BackendPlan";

/**
 * A paginated collection of plan objects
 */
export interface BackendPlanCollection extends CommonCollection<BackendPlan> {
}

