/**
 * BackendDatabaseRowCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {BackendDatabaseRow} from "./BackendDatabaseRow";

/**
 * A paginated collection of database rows
 */
export interface BackendDatabaseRowCollection extends CommonCollection<BackendDatabaseRow> {
}

