/**
 * BackendFirewallUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendFirewall} from "./BackendFirewall";

export interface BackendFirewallUpdate extends BackendFirewall {
}

