/**
 * BackendWebhookUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendWebhook} from "./BackendWebhook";

export interface BackendWebhookUpdate extends BackendWebhook {
}

