/**
 * BackendAgent automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendAgentMessage} from "./BackendAgentMessage";
import type {BackendAgentMessageBinary} from "./BackendAgentMessageBinary";
import type {BackendAgentMessageChoice} from "./BackendAgentMessageChoice";
import type {BackendAgentMessageObject} from "./BackendAgentMessageObject";
import type {BackendAgentMessageText} from "./BackendAgentMessageText";
import type {BackendAgentMessageToolCall} from "./BackendAgentMessageToolCall";

/**
 * This object represents an agent message
 */
export interface BackendAgent {
    id?: number
    origin?: number
    message?: BackendAgentMessageBinary|BackendAgentMessageChoice|BackendAgentMessageObject|BackendAgentMessageText|BackendAgentMessageToolCall
    insertDate?: string
}

