/**
 * BackendAgentContentText automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendAgentContent} from "./BackendAgentContent";

/**
 * Text agent message
 */
export interface BackendAgentContentText extends BackendAgentContent {
    type: "text"
    content?: string
}

