/**
 * BackendDatabaseTableIndex automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BackendDatabaseTableIndex {
    name?: string
    unique?: boolean
    columns?: Array<string>
}
