/**
 * BackendRoleCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendRole} from "./BackendRole";

export interface BackendRoleCollection extends CommonCollection<BackendRole> {
}

