/**
 * BackendUserUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendUser} from "./BackendUser";

export interface BackendUserUpdate extends BackendUser {
}

