/**
 * BackendSchemaCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendSchema} from "./BackendSchema";

/**
 * Payload for creating a new schema definition
 */
export interface BackendSchemaCreate extends BackendSchema {
}

