/**
 * BackendAgentMessageTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {BackendAgentInput} from "./BackendAgentInput";
import {BackendAgentMessageCollection} from "./BackendAgentMessageCollection";
import {BackendAgentOutput} from "./BackendAgentOutput";
import {CommonMessage} from "./CommonMessage";
import {CommonMessageException} from "./CommonMessageException";

export class BackendAgentMessageTag extends TagAbstract {
    /**
     * Returns a paginated list of agent messages
     *
     * @returns {Promise<BackendAgentMessageCollection>}
     * @throws {CommonMessageException}
     * @throws {ClientException}
     */
    public async getAll(agentId: string, parent?: number): Promise<BackendAgentMessageCollection> {
        const url = this.parser.url('/backend/agent/$agent_id<[0-9]+|^~>/message', {
            'agent_id': agentId,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'parent': parent,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as BackendAgentMessageCollection;
        }

        const statusCode = response.status;
        if (statusCode >= 0 && statusCode <= 999) {
            throw new CommonMessageException(await response.json() as CommonMessage);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Submits a new agent message
     *
     * @returns {Promise<BackendAgentOutput>}
     * @throws {CommonMessageException}
     * @throws {ClientException}
     */
    public async submit(agentId: string, payload: BackendAgentInput, parent?: number): Promise<BackendAgentOutput> {
        const url = this.parser.url('/backend/agent/$agent_id<[0-9]+|^~>/message', {
            'agent_id': agentId,
        });

        let request: HttpRequest = {
            url: url,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            params: this.parser.query({
                'parent': parent,
            }, [
            ]),
            data: payload
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as BackendAgentOutput;
        }

        const statusCode = response.status;
        if (statusCode >= 0 && statusCode <= 999) {
            throw new CommonMessageException(await response.json() as CommonMessage);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
