/**
 * BackendActionIndex automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendActionIndexEntry} from "./BackendActionIndexEntry";

/**
 * Contains all possible classes which can be used at an action as class
 */
export interface BackendActionIndex {
    actions?: Array<BackendActionIndexEntry>
}

