/**
 * BackendActionCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendAction} from "./BackendAction";

/**
 * A paginated collection of action objects
 */
export interface BackendActionCollection extends CommonCollection<BackendAction> {
}

