/**
 * BackendAgentContentToolCallFunction automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Concrete values for a function tool call
 */
export interface BackendAgentContentToolCallFunction {
    id?: string
    name?: string
    arguments?: string
}

