/**
 * BackendAppCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendApp} from "./BackendApp";

/**
 * A paginated collection of app objects
 */
export interface BackendAppCollection extends CommonCollection<BackendApp> {
}

