/**
 * BackendTransaction automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BackendTransaction {
    id?: number
    userId?: number
    planId?: number
    transactionId?: string
    amount?: number
    points?: number
    periodStart?: string
    periodEnd?: string
    insertDate?: string
}

