/**
 * BackendAgentContentChoice automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendAgentContent} from "./BackendAgentContent";
import type {BackendAgentContentBinary} from "./BackendAgentContentBinary";
import type {BackendAgentContentObject} from "./BackendAgentContentObject";
import type {BackendAgentContentText} from "./BackendAgentContentText";
import type {BackendAgentContentToolCall} from "./BackendAgentContentToolCall";

/**
 * Choice agent message
 */
export interface BackendAgentContentChoice extends BackendAgentContent {
    type: "choice"
    items?: Array<BackendAgentContentBinary|BackendAgentContentChoice|BackendAgentContentObject|BackendAgentContentText|BackendAgentContentToolCall>
}

