/**
 * BackendWebhookCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendWebhook} from "./BackendWebhook";

/**
 * Request payload to create a new webhook subscription
 */
export interface BackendWebhookCreate extends BackendWebhook {
}

