/**
 * BackendOperationUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendOperation} from "./BackendOperation";
export interface BackendOperationUpdate extends BackendOperation {
}
