/**
 * BackendDashboardUsers automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendDashboardUser} from "./BackendDashboardUser";
export type BackendDashboardUsers = CommonCollection<BackendDashboardUser>;
