/**
 * BackendAgentCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendAgent} from "./BackendAgent";

/**
 * Payload for creating a new AI agent
 */
export interface BackendAgentCreate extends BackendAgent {
}

