/**
 * BackendPlanUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendPlan} from "./BackendPlan";

export interface BackendPlanUpdate extends BackendPlan {
}

