/**
 * BackendWebhookCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendWebhook} from "./BackendWebhook";

/**
 * A paginated collection of webhook objects
 */
export interface BackendWebhookCollection extends CommonCollection<BackendWebhook> {
}

