/**
 * BackendConnectionCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendConnection} from "./BackendConnection";

/**
 * A paginated collection of connection objects
 */
export interface BackendConnectionCollection extends CommonCollection<BackendConnection> {
}

