/**
 * BackendPlan automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonMetadata} from "./CommonMetadata";

/**
 * This object represents a plan, a plan allows users to obtain points or in general subscribe to your app
 */
export interface BackendPlan {
    id?: number
    name?: string
    description?: string
    price?: number
    points?: number
    period?: number
    externalId?: string
    scopes?: Array<string>
    metadata?: CommonMetadata
}

