/**
 * BackendAgentMessageText automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendAgentMessage} from "./BackendAgentMessage";

/**
 * Text agent result
 */
export interface BackendAgentMessageText extends BackendAgentMessage {
    type: "text"
    content?: string
}

