/**
 * BackendPageCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendPage} from "./BackendPage";

/**
 * A paginated collection of page objects
 */
export interface BackendPageCollection extends CommonCollection<BackendPage> {
}

