/**
 * BackendFirewallCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendFirewall} from "./BackendFirewall";

export interface BackendFirewallCollection extends CommonCollection<BackendFirewall> {
}

