/**
 * BackendTrashData automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * This object represents a deleted item stored in the trash bin
 */
export interface BackendTrashData {
    id?: number
    status?: number
    name?: string
}

