/**
 * BackendConfigCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendConfig} from "./BackendConfig";
export type BackendConfigCollection = CommonCollection<BackendConfig>;
