/**
 * BackendCronjobCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendCronjob} from "./BackendCronjob";

export interface BackendCronjobCreate extends BackendCronjob {
}

