/**
 * BackendTransaction automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * This object represents a transaction. A transaction is generated by the system in case the payment provide provides a message that the payment was successfully executed
 */
export interface BackendTransaction {
    id?: number
    userId?: number
    planId?: number
    transactionId?: string
    amount?: number
    points?: number
    periodStart?: string
    periodEnd?: string
    insertDate?: string
}

