/**
 * BackendGeneratorProviderChangelog automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendSchema} from "./BackendSchema";
import type {BackendAction} from "./BackendAction";
import type {BackendOperation} from "./BackendOperation";

export interface BackendGeneratorProviderChangelog {
    schemas?: Array<BackendSchema>
    actions?: Array<BackendAction>
    operations?: Array<BackendOperation>
}

