/**
 * BackendOperationCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendOperation} from "./BackendOperation";

/**
 * Payload for creating a new operation entity
 */
export interface BackendOperationCreate extends BackendOperation {
}

