/**
 * BackendTestConfig automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendActionExecuteRequest} from "./BackendActionExecuteRequest";

/**
 * Configuration parameters for executing a test run
 */
export interface BackendTestConfig extends BackendActionExecuteRequest {
}

