/**
 * BackendBundleCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendBundle} from "./BackendBundle";

/**
 * Payload for creating a new configuration bundle
 */
export interface BackendBundleCreate extends BackendBundle {
}

