/**
 * BackendSchemaCommit automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendUser} from "./BackendUser";
import type {BackendSchemaSource} from "./BackendSchemaSource";

/**
 * A schema commit which represents a change in the schema source
 */
export interface BackendSchemaCommit {
    id?: number
    user?: BackendUser
    commitHash?: string
    schema?: BackendSchemaSource
    insertDate?: string
}

