/**
 * BackendActionCommit automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendUser} from "./BackendUser";
import type {BackendActionConfig} from "./BackendActionConfig";

/**
 * An action commit which represents a change in the action configuration
 */
export interface BackendActionCommit {
    id?: number
    user?: BackendUser
    commitHash?: string
    config?: BackendActionConfig
    insertDate?: string
}

