/**
 * BackendEventCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendEvent} from "./BackendEvent";
export interface BackendEventCreate extends BackendEvent {
}
