/**
 * BackendLogError automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BackendLogError {
    id?: number
    message?: number
    trace?: string
    file?: string
    line?: number
}

