/**
 * BackendCategoryCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendCategory} from "./BackendCategory";

/**
 * A paginated collection of category objects
 */
export interface BackendCategoryCollection extends CommonCollection<BackendCategory> {
}

