/**
 * BackendCategoryCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendCategory} from "./BackendCategory";

export interface BackendCategoryCreate extends BackendCategory {
}

