/**
 * BackendScopeCategories automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendScopeCategory} from "./BackendScopeCategory";

/**
 * Container for grouping available scopes into logical categories
 */
export interface BackendScopeCategories {
    categories?: Array<BackendScopeCategory>
}

