/**
 * BackendTransactionCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {BackendTransaction} from "./BackendTransaction";

/**
 * A paginated collection of transaction objects
 */
export interface BackendTransactionCollection extends CommonCollection<BackendTransaction> {
}

