/**
 * BackendOperationParameters automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendOperationSchema} from "./BackendOperationSchema";

/**
 * Map of path or query parameters accepted by the operation
 */
export interface BackendOperationParameters extends Record<string, BackendOperationSchema> {
}

