/**
 * BackendAppToken automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BackendAppToken {
    id?: number
    status?: number
    token?: string
    scope?: Array<string>
    ip?: string
    expire?: string
    date?: string
}
