/**
 * BackendTokenCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {BackendToken} from "./BackendToken";

/**
 * A paginated collection of token objects
 */
export interface BackendTokenCollection extends CommonCollection<BackendToken> {
}

