/**
 * BackendSdkMessage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Response structure detailing the outcome of an SDK generation job
 */
export interface BackendSdkMessage {
    kind?: string
    success?: boolean
    message?: string
    link?: string
}

