/**
 * BackendConnectionCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendConnection} from "./BackendConnection";

export interface BackendConnectionCreate extends BackendConnection {
}

