/**
 * BackendCronjobCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendCronjob} from "./BackendCronjob";

/**
 * Payload for creating a new cronjob
 */
export interface BackendCronjobCreate extends BackendCronjob {
}

