/**
 * BackendDashboard automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendStatisticChart} from "./BackendStatisticChart";

/**
 * Represents an object containing all widget data for the dashboard
 */
export interface BackendDashboard {
    errorsPerOperation?: BackendStatisticChart
    incomingRequests?: BackendStatisticChart
    incomingTransactions?: BackendStatisticChart
    mostUsedOperations?: BackendStatisticChart
    timePerOperation?: BackendStatisticChart
    testCoverage?: BackendStatisticChart
    mostUsedActivities?: BackendStatisticChart
    activitiesPerUser?: BackendStatisticChart
    userRegistrations?: BackendStatisticChart
}

