/**
 * BackendDashboardUser automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BackendDashboardUser {
    id?: number
    status?: string
    name?: string
    date?: string
}
