/**
 * BackendDatabaseTableCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {BackendDatabaseTable} from "./BackendDatabaseTable";

/**
 * A paginated collection of database table objects
 */
export interface BackendDatabaseTableCollection extends CommonCollection<BackendDatabaseTable> {
}

