/**
 * BackendPageCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendPage} from "./BackendPage";

export interface BackendPageCreate extends BackendPage {
}

