/**
 * BackendEventCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendEvent} from "./BackendEvent";
export type BackendEventCollection = CommonCollection<BackendEvent>;
