/**
 * BackendCronjobCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendCronjob} from "./BackendCronjob";

export interface BackendCronjobCollection extends CommonCollection<BackendCronjob> {
}

