/**
 * BackendOperationCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendOperation} from "./BackendOperation";
export type BackendOperationCollection = CommonCollection<BackendOperation>;
