/**
 * BackendIdentityIndex automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendIdentityIndexEntry} from "./BackendIdentityIndexEntry";

/**
 * Contains all possible classes which can be used at an identity as class
 */
export interface BackendIdentityIndex {
    providers?: Array<BackendIdentityIndexEntry>
}

