/**
 * BackendAccountChangePassword automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Payload required to update the current user's password
 */
export interface BackendAccountChangePassword {
    oldPassword?: string
    newPassword?: string
    verifyPassword?: string
}

