/**
 * BackendRateAllocation automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BackendRateAllocation {
    id?: number
    operationId?: number
    userId?: number
    planId?: number
    appId?: number
    authenticated?: boolean
}
