/**
 * BackendBackupImportResult automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BackendBackupImportResult {
    success?: boolean
    message?: string
    logs?: Array<string>
}

