/**
 * BackendRate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendRateAllocation} from "./BackendRateAllocation";
import {CommonMetadata} from "./CommonMetadata";

/**
 * This object represents a rate limitation, which allows to limit the requests which a user can send
 */
export interface BackendRate {
    id?: number
    priority?: number
    name?: string
    rateLimit?: number
    timespan?: string
    allocation?: Array<BackendRateAllocation>
    metadata?: CommonMetadata
}

