/**
 * BackendOperationCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {BackendOperation} from "./BackendOperation";

/**
 * A paginated collection of operation objects
 */
export interface BackendOperationCollection extends CommonCollection<BackendOperation> {
}

