/**
 * BackendCronjob automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonMetadata} from "./CommonMetadata";
import {BackendCronjobError} from "./BackendCronjobError";

/**
 * This object represents a cronjob which can invoke an action at a specific interval
 */
export interface BackendCronjob {
    id?: number
    name?: string
    cron?: string
    action?: string
    executeDate?: string
    exitCode?: number
    metadata?: CommonMetadata
    errors?: Array<BackendCronjobError>
}

