/**
 * BackendDashboardRequests automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendDashboardRequest} from "./BackendDashboardRequest";
export type BackendDashboardRequests = CommonCollection<BackendDashboardRequest>;
