/**
 * BackendActionExecuteResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendActionExecuteResponseHeaders} from "./BackendActionExecuteResponseHeaders";
import {BackendActionExecuteResponseBody} from "./BackendActionExecuteResponseBody";

export interface BackendActionExecuteResponse {
    statusCode?: number
    headers?: BackendActionExecuteResponseHeaders
    body?: BackendActionExecuteResponseBody
}

