/**
 * BackendTest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendTestConfig} from "./BackendTestConfig";

export interface BackendTest {
    id?: number
    status?: number
    operationName?: string
    message?: string
    response?: string
    config?: BackendTestConfig
}

