/**
 * BackendBundle automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendBundleConfig} from "./BackendBundleConfig";

/**
 * This object represents a bundle which allows you to submit action, schema, event, cronjob and trigger configuration from you local instance to the Fusio marketplace
 */
export interface BackendBundle {
    id?: number
    name?: string
    config?: BackendBundleConfig
}

