/**
 * BackendGeneratorProviderChangelog automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendSchema} from "./BackendSchema";
import {BackendAction} from "./BackendAction";
import {BackendOperation} from "./BackendOperation";

export interface BackendGeneratorProviderChangelog {
    schemas?: Array<BackendSchema>
    actions?: Array<BackendAction>
    operations?: Array<BackendOperation>
}

