/**
 * BackendStatisticChartSeries automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BackendStatisticChartSeries {
    name?: string
    data?: Array<number>
}

