/**
 * BackendSdkGenerate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Payload defining target format and configuration for triggering an SDK generation run
 */
export interface BackendSdkGenerate {
    format?: string
    config?: string
}

