/**
 * BackendEventSubscription automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendEventSubscriptionResponse} from "./BackendEventSubscriptionResponse";
export interface BackendEventSubscription {
    id?: number
    eventId?: number
    userId?: number
    endpoint?: string
    responses?: Array<BackendEventSubscriptionResponse>
}
