/**
 * BackendCronjobError automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Represents an error which occurred on cronjob execution
 */
export interface BackendCronjobError {
    message?: string
    trace?: string
    file?: string
    line?: number
}

