/**
 * BackendActionIndex automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendActionIndexEntry} from "./BackendActionIndexEntry";

export interface BackendActionIndex {
    actions?: Array<BackendActionIndexEntry>
}

