/**
 * BackendTokenCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendToken} from "./BackendToken";

export interface BackendTokenCollection extends CommonCollection<BackendToken> {
}

