/**
 * BackendBundleConfig automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Configuration settings and resource specs exported within the bundle
 */
export interface BackendBundleConfig extends Record<string, any> {
}

