/**
 * BackendActionUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendAction} from "./BackendAction";
export interface BackendActionUpdate extends BackendAction {
}
