/**
 * BackendForm automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonMetadata} from "./CommonMetadata";

export interface BackendForm {
    id?: number
    status?: number
    name?: string
    operationId?: number
    uiSchema?: any
    metadata?: CommonMetadata
}

