/**
 * BackendWebhookUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendWebhook} from "./BackendWebhook";

/**
 * Request payload to update an existing webhook subscription
 */
export interface BackendWebhookUpdate extends BackendWebhook {
}

