/**
 * BackendOperationSchema automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Defines primitive type constraints for parameter schema definitions
 */
export interface BackendOperationSchema {
    description?: string
    type?: string
    format?: string
    enum?: string
}

