/**
 * BackendCronjobCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {BackendCronjob} from "./BackendCronjob";

/**
 * A paginated collection of cronjob objects
 */
export interface BackendCronjobCollection extends CommonCollection<BackendCronjob> {
}

