/**
 * BackendLog automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendLogError} from "./BackendLogError";
export interface BackendLog {
    id?: number
    ip?: string
    userAgent?: string
    method?: string
    path?: string
    header?: string
    body?: string
    date?: string
    errors?: Array<BackendLogError>
}
