/**
 * BackendSdkResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendSdkTypes} from "./BackendSdkTypes";

/**
 * Container listing target SDK languages or formats available for generator execution
 */
export interface BackendSdkResponse {
    kind?: string
    types?: BackendSdkTypes
}

