/**
 * BackendAgentMessage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendAgentMessageBinary} from "./BackendAgentMessageBinary";
import type {BackendAgentMessageChoice} from "./BackendAgentMessageChoice";
import type {BackendAgentMessageObject} from "./BackendAgentMessageObject";
import type {BackendAgentMessageText} from "./BackendAgentMessageText";
import type {BackendAgentMessageToolCall} from "./BackendAgentMessageToolCall";

/**
 * Agent call result
 */
export interface BackendAgentMessage {
    type?: string
    metadata?: Record<string, any>
}

