/**
 * BackendTaxonomyMove automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Moves the provided objects to a taxonomy
 */
export interface BackendTaxonomyMove {
    operations?: Array<number>
    actions?: Array<number>
    events?: Array<number>
    cronjobs?: Array<number>
    triggers?: Array<number>
}

