/**
 * BackendSpecificationChangelog automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Represents structural changelog differences between specification versions
 */
export interface BackendSpecificationChangelog {
    master?: any
    tag?: any
    version?: string
    changelog?: string
}

