/**
 * BackendGeneratorProviderConfig automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Arbitrary configuration map for the generator provider
 */
export interface BackendGeneratorProviderConfig extends Record<string, any> {
}

