/**
 * BackendIdentityCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendIdentity} from "./BackendIdentity";

export interface BackendIdentityCreate extends BackendIdentity {
}

