/**
 * BackendAuditObject automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * A key value object containing the changes
 */
export type BackendAuditObject = Record<string, any>;
