/**
 * BackendTrashData automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BackendTrashData {
    id?: number
    status?: number
    name?: string
}
