/**
 * BackendCategoryCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendCategory} from "./BackendCategory";

/**
 * Payload for creating a new category
 */
export interface BackendCategoryCreate extends BackendCategory {
}

