/**
 * BackendScopeCategoryScope automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BackendScopeCategoryScope {
    id?: number
    name?: string
    description?: string
}
