/**
 * BackendEventSubscriptionCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendEventSubscription} from "./BackendEventSubscription";
export type BackendEventSubscriptionCollection = CommonCollection<BackendEventSubscription>;
