/**
 * BackendBundleCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendBundle} from "./BackendBundle";

/**
 * A paginated collection of bundle objects
 */
export interface BackendBundleCollection extends CommonCollection<BackendBundle> {
}

