/**
 * BackendActionExecuteRequestBody automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Represents a request body
 */
export interface BackendActionExecuteRequestBody extends Record<string, any> {
}

