/**
 * BackendRoleUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendRole} from "./BackendRole";

/**
 * Payload for updating an existing user role entity
 */
export interface BackendRoleUpdate extends BackendRole {
}

