/**
 * BackendFirewallCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {BackendFirewall} from "./BackendFirewall";

/**
 * A paginated collection of firewall objects
 */
export interface BackendFirewallCollection extends CommonCollection<BackendFirewall> {
}

