/**
 * BackendScopeCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {BackendScope} from "./BackendScope";

export interface BackendScopeCollection extends CommonCollection<BackendScope> {
}

