/**
 * BackendCronjobUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendCronjob} from "./BackendCronjob";

export interface BackendCronjobUpdate extends BackendCronjob {
}

