/**
 * BackendAgentTools automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendAgentTool} from "./BackendAgentTool";

/**
 * Represents a collection of available tools
 */
export interface BackendAgentTools {
    tools?: Array<BackendAgentTool>
}

