/**
 * BackendStatisticCount automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Represents an aggregated count metric over a specific timeframe
 */
export interface BackendStatisticCount {
    count?: number
    from?: string
    to?: string
}

