/**
 * BackendFormCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BackendForm} from "./BackendForm";

export interface BackendFormCreate extends BackendForm {
}

