/**
 * BackendGeneratorIndexProviders automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendGeneratorIndexProvider} from "./BackendGeneratorIndexProvider";

/**
 * Contains all possible classes which can be used at an generator as class
 */
export interface BackendGeneratorIndexProviders {
    providers?: Array<BackendGeneratorIndexProvider>
}

