/**
 * BackendPageUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BackendPage} from "./BackendPage";

export interface BackendPageUpdate extends BackendPage {
}

