/**
 * BackendPage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonMetadata} from "./CommonMetadata";

export interface BackendPage {
    id?: number
    status?: number
    title?: string
    slug?: string
    content?: string
    metadata?: CommonMetadata
}

