/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {ClientAbstract, TokenStoreInterface} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {AuthorizationTag} from "./AuthorizationTag";
import {SystemTag} from "./SystemTag";
import {ConsumerTag} from "./ConsumerTag";
import {BackendTag} from "./BackendTag";

export class Client extends ClientAbstract {
    public authorization(): AuthorizationTag
    {
        return new AuthorizationTag(
            this.httpClient,
            this.parser
        );
    }

    public system(): SystemTag
    {
        return new SystemTag(
            this.httpClient,
            this.parser
        );
    }

    public consumer(): ConsumerTag
    {
        return new ConsumerTag(
            this.httpClient,
            this.parser
        );
    }

    public backend(): BackendTag
    {
        return new BackendTag(
            this.httpClient,
            this.parser
        );
    }



}
