/**
 * CommonFormElementConnection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonFormElementSelect} from "./CommonFormElementSelect";

/**
 * Form element which represents a connection selection
 */
export interface CommonFormElementConnection extends CommonFormElementSelect {
    type: "connection"
}

