/**
 * CommonFormElement automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface CommonFormElement {
    type?: string
    element?: string
    name?: string
    title?: string
    help?: string
}

