/**
 * CommonAgentContentObject automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonAgentContent} from "./CommonAgentContent";

/**
 * Structured agent message
 */
export interface CommonAgentContentObject extends CommonAgentContent {
    type: "object"
    payload?: any
}

