/**
 * CommonFormContainer automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonFormElementInput} from "./CommonFormElementInput";
import {CommonFormElementSelect} from "./CommonFormElementSelect";
import {CommonFormElementTag} from "./CommonFormElementTag";
import {CommonFormElementTextArea} from "./CommonFormElementTextArea";
export interface CommonFormContainer {
    element?: Array<CommonFormElementInput | CommonFormElementSelect | CommonFormElementTag | CommonFormElementTextArea>
}
