/**
 * CommonAgentContentBinary automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonAgentContent} from "./CommonAgentContent";

/**
 * Binary agent message
 */
export interface CommonAgentContentBinary extends CommonAgentContent {
    type: "binary"
    mime?: string
    data?: string
}

