/**
 * CommonFormElementSelect automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonFormElement} from "./CommonFormElement";
import {CommonFormElementSelectOption} from "./CommonFormElementSelectOption";
export interface CommonFormElementSelect extends CommonFormElement {
    options?: Array<CommonFormElementSelectOption>
}
