/**
 * CommonFormElementSelect automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonFormElement} from "./CommonFormElement";
import type {CommonFormElementSelectOption} from "./CommonFormElementSelectOption";

/**
 * Form element which represents a select element
 */
export interface CommonFormElementSelect extends CommonFormElement {
    type: "select"
    options?: Array<CommonFormElementSelectOption>
}

