/**
 * CommonFormElement automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonFormElementInput} from "./CommonFormElementInput";
import {CommonFormElementSelect} from "./CommonFormElementSelect";
import {CommonFormElementTag} from "./CommonFormElementTag";
import {CommonFormElementTextArea} from "./CommonFormElementTextArea";

export interface CommonFormElement {
    type?: string
    element?: string
    name?: string
    title?: string
    help?: string
}

