/**
 * CommonMessage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface CommonMessage {
    success?: boolean
    message?: string
    id?: string
}
