/**
 * CommonFormElementTypeAPI automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonFormElement} from "./CommonFormElement";

/**
 * Form element which represents a TypeAPI editor
 */
export interface CommonFormElementTypeAPI extends CommonFormElement {
    type: "typeapi"
}

