/**
 * CommonAgentInput automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonAgentContent} from "./CommonAgentContent";
import type {CommonAgentContentBinary} from "./CommonAgentContentBinary";
import type {CommonAgentContentChoice} from "./CommonAgentContentChoice";
import type {CommonAgentContentObject} from "./CommonAgentContentObject";
import type {CommonAgentContentText} from "./CommonAgentContentText";
import type {CommonAgentContentToolCall} from "./CommonAgentContentToolCall";

/**
 * This object represents an agent input
 */
export interface CommonAgentInput {
    previousId?: string
    input?: CommonAgentContentBinary|CommonAgentContentChoice|CommonAgentContentObject|CommonAgentContentText|CommonAgentContentToolCall
}

