/**
 * CommonFormElementAgent automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonFormElementSelect} from "./CommonFormElementSelect";

/**
 * Form element which represents an agent selection
 */
export interface CommonFormElementAgent extends CommonFormElementSelect {
    type: "agent"
}

