/**
 * ConsumerScopeCategory automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ConsumerScopeCategoryScope} from "./ConsumerScopeCategoryScope";

export interface ConsumerScopeCategory {
    id?: number
    name?: string
    scopes?: Array<ConsumerScopeCategoryScope>
}

