/**
 * ConsumerEvent automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonMetadata} from "./CommonMetadata";

/**
 * Represents an event trigger definition within the platform
 */
export interface ConsumerEvent {
    kind?: string
    id?: number
    name?: string
    description?: string
    metadata?: CommonMetadata
}

