/**
 * ConsumerUserEmail automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Payload used to initiate account recovery or email requests
 */
export interface ConsumerUserEmail {
    email?: string
    captcha?: string
}

