/**
 * ConsumerAppUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Payload for updating an existing consumer application
 */
export interface ConsumerAppUpdate {
    name?: string
    url?: string
    scopes?: Array<string>
}

