/**
 * ConsumerTransaction automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ConsumerPlan} from "./ConsumerPlan";
export interface ConsumerTransaction {
    id?: number
    userId?: number
    planId?: number
    plan?: ConsumerPlan
    transactionId?: string
    amount?: number
    points?: number
    periodStart?: string
    periodEnd?: string
    insertDate?: string
}
