/**
 * ConsumerEventSubscriptionResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface ConsumerEventSubscriptionResponse {
    status?: number
    code?: number
    attempts?: string
    executeDate?: string
}
