/**
 * ConsumerWebhookCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {ConsumerWebhook} from "./ConsumerWebhook";
export type ConsumerWebhookCollection = CommonCollection<ConsumerWebhook>;
