/**
 * ConsumerGrantCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {ConsumerGrant} from "./ConsumerGrant";

/**
 * Collection of user authorization grant records
 */
export interface ConsumerGrantCollection extends CommonCollection<ConsumerGrant> {
}

