/**
 * ConsumerWebhookUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface ConsumerWebhookUpdate {
    event?: string
    name?: string
    endpoint?: string
}

