/**
 * ConsumerPage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonMetadata} from "./CommonMetadata";

export interface ConsumerPage {
    id?: number
    title?: string
    slug?: string
    content?: string
    metadata?: CommonMetadata
}

