/**
 * ConsumerLogCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {ConsumerLog} from "./ConsumerLog";

/**
 * Collection of access log records
 */
export interface ConsumerLogCollection extends CommonCollection<ConsumerLog> {
}

