/**
 * ConsumerLog automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Access log entry recording an incoming HTTP request
 */
export interface ConsumerLog {
    kind?: string
    id?: number
    appId?: number
    ip?: string
    userAgent?: string
    method?: string
    path?: string
    header?: string
    body?: string
    date?: string
}

