/**
 * ConsumerAgentMessageCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {ConsumerAgentMessage} from "./ConsumerAgentMessage";

/**
 * Represents a collection of agent messages
 */
export interface ConsumerAgentMessageCollection extends CommonCollection<ConsumerAgentMessage> {
}

