/**
 * ConsumerAuthorizeRequest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface ConsumerAuthorizeRequest {
    responseType: string
    clientId: string
    redirectUri?: string
    scope: string
    state?: string
    allow: boolean
}
