/**
 * ConsumerUserRegister automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Payload for registering a new user account
 */
export interface ConsumerUserRegister {
    name?: string
    email?: string
    password?: string
    captcha?: string
}

