/**
 * ConsumerUserActivate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Payload used to activate a user account via token
 */
export interface ConsumerUserActivate {
    token?: string
}

