/**
 * ConsumerAgent automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * This object represents an agent
 */
export interface ConsumerAgent {
    kind?: string
    id?: number
    name?: string
    description?: string
}

