/**
 * ConsumerEventCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {ConsumerEvent} from "./ConsumerEvent";
export type ConsumerEventCollection = CommonCollection<ConsumerEvent>;
