/**
 * ConsumerScope automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonMetadata} from "./CommonMetadata";

export interface ConsumerScope {
    id?: number
    name?: string
    description?: string
    metadata?: CommonMetadata
}

