/**
 * ConsumerPaymentPortalRequest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Request payload to launch the billing management portal
 */
export interface ConsumerPaymentPortalRequest {
    returnUrl?: string
}

