/**
 * ConsumerEventSubscriptionCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {ConsumerEventSubscription} from "./ConsumerEventSubscription";
export type ConsumerEventSubscriptionCollection = CommonCollection<ConsumerEventSubscription>;
