/**
 * ConsumerScopeCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {ConsumerScope} from "./ConsumerScope";

/**
 * Collection of API permission scopes
 */
export interface ConsumerScopeCollection extends CommonCollection<ConsumerScope> {
}

