/**
 * ConsumerAuthorizeResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ConsumerAuthorizeResponseToken} from "./ConsumerAuthorizeResponseToken";
export interface ConsumerAuthorizeResponse {
    type?: string
    token?: ConsumerAuthorizeResponseToken
    code?: string
    redirectUri?: string
}
