/**
 * ConsumerTokenCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Payload for issuing a new personal access token
 */
export interface ConsumerTokenCreate {
    name?: string
    scopes?: Array<string>
    expire?: string
}

