/**
 * ConsumerApp automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonMetadata} from "./CommonMetadata";
export interface ConsumerApp {
    id?: number
    userId?: number
    status?: number
    name?: string
    url?: string
    appKey?: string
    appSecret?: string
    date?: string
    scopes?: Array<string>
    metadata?: CommonMetadata
}
