/**
 * ConsumerAppCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Payload for creating a new consumer application
 */
export interface ConsumerAppCreate {
    name?: string
    url?: string
    scopes?: Array<string>
}

