/**
 * ConsumerEventCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {ConsumerEvent} from "./ConsumerEvent";

export interface ConsumerEventCollection extends CommonCollection<ConsumerEvent> {
}

