/**
 * ConsumerForm automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonMetadata} from "./CommonMetadata";

export interface ConsumerForm {
    id?: number
    name?: string
    action?: string
    method?: string
    jsonSchema?: any
    uiSchema?: any
    metadata?: CommonMetadata
}

