/**
 * ConsumerIdentity automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Identity provider configuration for single sign-on
 */
export interface ConsumerIdentity {
    kind?: string
    id?: number
    name?: string
    icon?: string
    redirect?: string
}

