/**
 * ConsumerAuthorizeMeta automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ConsumerScope} from "./ConsumerScope";
export interface ConsumerAuthorizeMeta {
    name?: string
    url?: string
    scopes?: Array<ConsumerScope>
}
