/**
 * ConsumerToken automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface ConsumerToken {
    id?: number
    status?: number
    name?: string
    scopes?: Array<string>
    ip?: string
    expire?: string
    date?: string
}

