/**
 * ConsumerGrant automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {ConsumerApp} from "./ConsumerApp";

/**
 * Represents user authorization granted to a consumer application
 */
export interface ConsumerGrant {
    kind?: string
    id?: number
    app?: ConsumerApp
    createDate?: string
}

