/**
 * ConsumerPlan automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonMetadata} from "./CommonMetadata";

/**
 * Subscription or monetization plan for API consumers
 */
export interface ConsumerPlan {
    kind?: string
    id?: number
    name?: string
    description?: string
    price?: number
    points?: number
    period?: number
    metadata?: CommonMetadata
}

