/**
 * ConsumerPaymentCheckoutRequest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Request payload to initiate a checkout flow for a plan
 */
export interface ConsumerPaymentCheckoutRequest {
    planId?: number
    returnUrl?: string
}

