/**
 * ConsumerScopeCategories automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ConsumerScopeCategory} from "./ConsumerScopeCategory";

export interface ConsumerScopeCategories {
    categories?: Array<ConsumerScopeCategory>
}

