/**
 * ConsumerIdentityCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {CommonCollection} from "./CommonCollection";
import type {ConsumerIdentity} from "./ConsumerIdentity";

export interface ConsumerIdentityCollection extends CommonCollection<ConsumerIdentity> {
}

