/**
 * ConsumerFormCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonCollection} from "./CommonCollection";
import {ConsumerForm} from "./ConsumerForm";

export interface ConsumerFormCollection extends CommonCollection<ConsumerForm> {
}

