/**
 * MarketplaceBundleCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {MarketplaceCollection} from "./MarketplaceCollection";
import {MarketplaceBundle} from "./MarketplaceBundle";

export interface MarketplaceBundleCollection extends MarketplaceCollection<MarketplaceBundle> {
}

