/**
 * MarketplaceObject automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {MarketplaceUser} from "./MarketplaceUser";
export interface MarketplaceObject {
    id?: number
    name?: string
    author?: MarketplaceUser
    version?: string
    icon?: string
    summary?: string
    description?: string
    cost?: number
    updateDate?: string
    insertDate?: string
}
