/**
 * MarketplaceAction automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {MarketplaceObject} from "./MarketplaceObject";
import {MarketplaceActionConfig} from "./MarketplaceActionConfig";

export interface MarketplaceAction extends MarketplaceObject {
    class?: string
    config?: MarketplaceActionConfig
}

