/**
 * MarketplaceBundleSchema automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {MarketplaceBundleSchemaSource} from "./MarketplaceBundleSchemaSource";

export interface MarketplaceBundleSchema {
    name?: string
    source?: MarketplaceBundleSchemaSource
}

