/**
 * MarketplaceBundleConfig automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {MarketplaceBundleAction} from "./MarketplaceBundleAction";
import type {MarketplaceBundleSchema} from "./MarketplaceBundleSchema";
import type {MarketplaceBundleEvent} from "./MarketplaceBundleEvent";
import type {MarketplaceBundleCronjob} from "./MarketplaceBundleCronjob";
import type {MarketplaceBundleTrigger} from "./MarketplaceBundleTrigger";

export interface MarketplaceBundleConfig {
    actions?: Array<MarketplaceBundleAction>
    schemas?: Array<MarketplaceBundleSchema>
    events?: Array<MarketplaceBundleEvent>
    cronjobs?: Array<MarketplaceBundleCronjob>
    triggers?: Array<MarketplaceBundleTrigger>
}

