/**
 * MarketplaceCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface MarketplaceCollection<T> {
    totalResults?: number
    startIndex?: number
    itemsPerPage?: number
    entry?: Array<T>
}
