/**
 * MarketplaceBundleCronjob automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface MarketplaceBundleCronjob {
    name?: string
    cron?: string
    action?: string
}

