/**
 * MarketplaceActionCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {MarketplaceCollection} from "./MarketplaceCollection";
import {MarketplaceAction} from "./MarketplaceAction";

export interface MarketplaceActionCollection extends MarketplaceCollection<MarketplaceAction> {
}

