/**
 * MarketplaceBundleSchemaSource automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface MarketplaceBundleSchemaSource extends Record<string, any> {
}

