/**
 * SystemRoutePath automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {SystemRouteMethod} from "./SystemRouteMethod";

export interface SystemRoutePath extends Record<string, SystemRouteMethod> {
}

