/**
 * SystemSchema automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {SystemSchemaTypeSchema} from "./SystemSchemaTypeSchema";
import {SystemSchemaForm} from "./SystemSchemaForm";
export interface SystemSchema {
    schema?: SystemSchemaTypeSchema
    form?: SystemSchemaForm
}
