/**
 * SystemOAuthConfiguration automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface SystemOAuthConfiguration {
    issuer?: string
    token_endpoint?: string
    token_endpoint_auth_methods_supported?: Array<string>
    userinfo_endpoint?: string
    scopes_supported?: Array<string>
    claims_supported?: Array<string>
}
