/**
 * SystemRoutePath automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {SystemRouteMethod} from "./SystemRouteMethod";
export type SystemRoutePath = Record<string, SystemRouteMethod>;
