/**
 * SystemCaptchaTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {CommonMessage} from "./CommonMessage";
import {CommonMessageException} from "./CommonMessageException";
import {SystemCaptchaChallenge} from "./SystemCaptchaChallenge";

export class SystemCaptchaTag extends TagAbstract {
    /**
     * Endpoint to generate a captcha challenge
     *
     * @returns {Promise<SystemCaptchaChallenge>}
     * @throws {CommonMessageException}
     * @throws {ClientException}
     */
    public async challenge(): Promise<SystemCaptchaChallenge> {
        const url = this.parser.url('/system/captcha/challenge', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as SystemCaptchaChallenge;
        }

        const statusCode = response.status;
        if (statusCode >= 0 && statusCode <= 999) {
            throw new CommonMessageException(await response.json() as CommonMessage);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
