/**
 * SystemAPICatalogLinkSet automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {SystemAPICatalogLink} from "./SystemAPICatalogLink";

export interface SystemAPICatalogLinkSet {
    anchor?: string
    "service-desc"?: Array<SystemAPICatalogLink>
    "service-doc"?: Array<SystemAPICatalogLink>
    "service-meta"?: Array<SystemAPICatalogLink>
    status?: Array<SystemAPICatalogLink>
}

